### ISSUE TITLE
config app-name in file setting.yaml, can used resource`s namespace, so namespace should config different with app-name

### ISSUE THREAD

**Issue by ddh-open** [KusionStack/konfig#120]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SparkYuan** [comment]
@ddh-open please add more details about this issue and answer questions in the template.
