### ISSUE TITLE
Manual approval required for workflow run 9499877053: Deploying example/ai-agent-demo/dev

### ISSUE THREAD

**Issue by liu-hm19** [KusionStack/konfig#164]
Please check the preview report at: https://github.com/KusionStack/konfig/actions/runs/9499877053/artifacts/1598016591

Workflow is pending manual review.
URL: https://api.github.com/KusionStack/konfig/actions/runs/9499877053

Required approvers: [SparkYuan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by SparkYuan** [comment]
approved

**Comment by liu-hm19** [comment]
All approvers have approved, continuing workflow and closing this issue.
