### ISSUE TITLE
[Bugfix] Mixin use pkg.identfier merge error 

### ISSUE THREAD

**Issue by Peefy** [KusionStack/konfig#28]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

* test.k

```kcl
import pkg

mixin XMixin:
    server: pkg.Server {}
```

### 2. What did you expect to see? (Required)

Compile successed.

### 3. What did you see instead (Required)

```
KCL Compile Error[E2L23] : A complie error occurs during compiling
---> File test.k:4:5
4 |    server: pkg.Server {}
     5 ^  -> Failure
'pkg' refers to a value, but is being used as a type here
```

I use the code below to walk around and need KCLVM to fix this:

```kcl
import pkg

mixin XMixin:
    if True:
        server: pkg.Server {}
```

### 4. What is your KusionStack components version? (Required)

kclvm version is 0.4.2

**Comment by Peefy** [comment]
If `server` is deined in schema, we can write code as follows:
```kcl
server: pkg.Server = pkg.Server {}
```

**Comment by Peefy** [comment]
fixed in https://github.com/KusionStack/KCLVM/pull/159

**Comment by LeoLiuYan** [comment]
> If `server` is deined in schema, we can write code as follows:
> 
> ```
> server: pkg.Server = pkg.Server {}
> ```

If code in `pkg.Server` as
```
schema NewServer:
    server:  frontend.Server {
        workloadType = "deployment"
    }
```

and, we write code in `XMixin` as 
```
mixin XMixin:
    if True:
        server:  frontend.Server {
           image = "xxxx"
          mainContainer = {}
       }
```

then, we execute `kusion compile`, it reports
```
attribute 'image' of Server is required and can't be None or Undefined
```

When we execute `kusion compile`,  the values in `schema` and `mixin`  not merged?

@Peefy

**Comment by Peefy** [comment]
> > If `server` is deined in schema, we can write code as follows:
> > ```
> > server: pkg.Server = pkg.Server {}
> > ```
> 
> If code in `pkg.Server` as
> 
> ```
> schema NewServer:
>     server:  frontend.Server {
>         workloadType = "deployment"
>     }
> ```
> 
> and, we write code in `XMixin` as
> 
> ```
> mixin XMixin:
>     if True:
>         server:  frontend.Server {
>            image = "xxxx"
>            mainContainer = {}
>        }
> ```
> 
> then, we execute `kusion compile`, it reports
> 
> ```
> attribute 'image' of Server is required and can't be None or Undefined
> ```
> 
> When we execute `kusion compile`, the values in `schema` and `mixin` not merged?
> 
> @Peefy

@LeoLiuYan   Here, the `Server` instance will first be created in `NewServer`, where the check fails. U can write:
> If code in `pkg.Server` as
> 
> ```
> schema NewServer:
>.    mixin [XMixin]
>     server:  frontend.Server = frontend.Server {
>.        image = input.image or "default_image"
>         workloadType = "deployment"
>     }
> ```
> 
> and, we write code in `XMixin` as
> 
> ```
> mixin XMixin:
>     if True:
>         server:  frontend.Server {
>            image = "xxxx"
>            mainContainer = {}
>        }
> ```

**Comment by LeoLiuYan** [comment]
It works, but is redundant.
Is it possible to join first before `the check`,  when a shema includes `mixin`?

@Peefy

**Comment by Peefy** [comment]
> It works, but is redundant. Is it possible to join first before `the check`, when a shema includes `mixin`?
> 
> @Peefy

@LeoLiuYan Sure, we will design and optimize this feature with corresponding language proposals in the future.

**Comment by LeoLiuYan** [comment]
> > It works, but is redundant. Is it possible to join first before `the check`, when a shema includes `mixin`?
> > @Peefy
> 
> @LeoLiuYan Sure, we will design and optimize this feature with corresponding language proposals in the future.

Cool~   Expect to use this convenient feature!

**Comment by Peefy** [comment]
Related KCLVM Issue: https://github.com/KusionStack/KCLVM/issues/92
