### ISSUE TITLE
Add schema KubeVelaAppConfig to support KubeVela App and IaaS resources

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/konfig#87]
## Enhancement
Add shcema `KubeVelaAppConfig` like the existed schema `Server` to support both KubeVela and IaaS resources. We can convert K8s resources to KubeVela Application and Iaas resources to TF resources. 

More details can be found here https://github.com/kubevela/kubevela/issues/5219

**Comment by SparkYuan** [comment]
Ref:  https://github.com/KusionStack/konfig/pull/86

@howieyuen @liu-hm19

**Comment by liu-hm19** [comment]
As proposed in [kubevela/kubevela#5219](https://github.com/kubevela/kubevela/issues/5219), K8s related resources in KubeVelaAppConfig will be interpreted into a KubeVela Application model, and TF related resources will be interpreted into a Kusion Spec for IaaS resources, oss for instance. Thus the example of wordpress (Ref: [#86](https://github.com/KusionStack/konfig/pull/86)) will be interpreted into Kusion Spec with two types of resources, as sampled below: 

Stack: dev  ID                                                                                                                                     Action
 * ├─       aliyun:alicloud:alicloud_oss_bucket:kusion-oss                                                            Create
 * ├─       core.oam.dev/v1beta1:Application:wordpress-example:wordpress                             Create

**Comment by howieyuen** [comment]
Kubevela provides a user guide, [Provision and Binding Database](https://kubevela.io/docs/end-user/components/cloud-services/provision-and-consume-database), which provide cloud resources across k8s and TF. It's quite similar with our situation.

**Comment by liu-hm19** [comment]
Added supports for kubevela application in server frontend and render: #88
